-- MySQL Script generated by MySQL Workbench
-- Sun Jul  8 16:10:21 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ypack
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ypack`
  DEFAULT CHARACTER SET utf8;
USE `ypack`;

-- -----------------------------------------------------
-- Table `ypack`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ypack`.`author` (
  `id`      INT          NOT NULL AUTO_INCREMENT,
  `name`    VARCHAR(50)  NOT NULL,
  `contact` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ypack`.`package`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ypack`.`package` (
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `name`        VARCHAR(25)  NOT NULL,
  `description` VARCHAR(200) NOT NULL,
  `website`     VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

CREATE INDEX `idx_package_name`
  ON `ypack`.`package` (`name` ASC);

-- -----------------------------------------------------
-- Table `ypack`.`version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ypack`.`version` (
  `id`         INT          NOT NULL AUTO_INCREMENT,
  `name`       VARCHAR(25)  NOT NULL,
  `url`        VARCHAR(255) NOT NULL,
  `checksum`   VARCHAR(255) NULL,
  `os`         VARCHAR(10)  NOT NULL,
  `arch`       VARCHAR(10)  NOT NULL,
  `package_id` INT          NOT NULL,
  PRIMARY KEY (`id`, `package_id`),
  CONSTRAINT `fk_version_package`
  FOREIGN KEY (`package_id`)
  REFERENCES `ypack`.`package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `checksum_UNIQUE`
  ON `ypack`.`version` (`checksum` ASC);

CREATE INDEX `idx_version_name`
  ON `ypack`.`version` (`name` ASC);

CREATE INDEX `fk_version_package_idx`
  ON `ypack`.`version` (`package_id` ASC);

-- -----------------------------------------------------
-- Table `ypack`.`package_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ypack`.`package_author` (
  `package_id` INT NOT NULL,
  `author_id`  INT NOT NULL,
  PRIMARY KEY (`package_id`, `author_id`),
  CONSTRAINT `fk_package_has_author_package`
  FOREIGN KEY (`package_id`)
  REFERENCES `ypack`.`package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_package_has_author_author`
  FOREIGN KEY (`author_id`)
  REFERENCES `ypack`.`author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE INDEX `fk_package_author_author_idx`
  ON `ypack`.`package_author` (`author_id` ASC);

CREATE INDEX `fk_package_author_package_idx`
  ON `ypack`.`package_author` (`package_id` ASC);

-- -----------------------------------------------------
-- Table `ypack`.`alias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ypack`.`alias` (
  `id`         INT         NOT NULL AUTO_INCREMENT,
  `name`       VARCHAR(25) NOT NULL,
  `package_id` INT         NOT NULL,
  PRIMARY KEY (`id`, `package_id`),
  CONSTRAINT `fk_alias_package`
  FOREIGN KEY (`package_id`)
  REFERENCES `ypack`.`package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE INDEX `fk_alias_package_idx`
  ON `ypack`.`alias` (`package_id` ASC);

CREATE INDEX `idx_alias_name`
  ON `ypack`.`alias` (`name` ASC);


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
